import nodemailer from "nodemailer";

const getEnv = (key: string): string => {
  return (process.env as Record<string, string | undefined>)[key] || "";
};

const smtpHost = getEnv("SMTP_HOST");
const smtpPort = Number(getEnv("SMTP_PORT") || 587);
const smtpUser = getEnv("SMTP_USER");
const smtpPassword = getEnv("SMTP_PASSWORD");

const transporter =
  smtpHost && smtpUser && smtpPassword
    ? nodemailer.createTransport({
        host: smtpHost,
        port: smtpPort,
        secure: smtpPort === 465,
        auth: {
          user: smtpUser,
          pass: smtpPassword,
        },
      })
    : null;

/* -------------------------------------------------------------------------- */
/* EMAIL SENDER                                                               */
/* -------------------------------------------------------------------------- */

export const sendEmail = async (
  to: string,
  subject: string,
  html: string,
) => {
  try {
    if (!transporter) {
      console.log(
        `[Email Simulation] To: ${to} | Subject: ${subject}`,
      );
      return true;
    }

    const from =
      getEnv("EMAIL_FROM") ||
      getEnv("EMAIL_USER") ||
      "no-reply@example.com";

    await transporter.sendMail({
      from,
      to,
      subject,
      html,
    });

    console.log(`Email sent successfully to ${to}`);
    return true;
  } catch (error) {
    console.error("Email send error:", error);
    return false;
  }
};

/* -------------------------------------------------------------------------- */
/* ADMIN NOTIFICATION                                                         */
/* -------------------------------------------------------------------------- */

export const sendAdminNotification = async (
  subject: string,
  html: string,
) => {
  const adminEmail = getEnv("ADMIN_EMAIL");

  if (!adminEmail) {
    console.log(
      `[Admin Email Simulation] Subject: ${subject}`,
    );
    return true;
  }

  return sendEmail(
    adminEmail,
    `[PROJECT DEMO] ${subject}`,
    html,
  );
};

/* -------------------------------------------------------------------------- */
/* SHARED EMAIL DESIGN                                                        */
/* -------------------------------------------------------------------------- */

const emailLayout = (
  title: string,
  content: string,
) => `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${title}</title>
</head>

<body style="
  margin:0;
  padding:0;
  background:#f1f5f9;
  font-family:Arial,Helvetica,sans-serif;
  color:#0f172a;
">

  <div style="
    max-width:620px;
    margin:40px auto;
    background:#ffffff;
    border-radius:16px;
    overflow:hidden;
    box-shadow:0 8px 30px rgba(15,23,42,0.08);
  ">

    <!-- HEADER -->
    <div style="
      background:linear-gradient(135deg,#2563eb,#4f46e5);
      padding:32px 24px;
      text-align:center;
      color:white;
    ">

      <div style="
        display:inline-block;
        background:rgba(255,255,255,0.15);
        padding:8px 14px;
        border-radius:999px;
        font-size:12px;
        font-weight:bold;
        letter-spacing:0.5px;
        margin-bottom:14px;
      ">
        FULL-STACK PROJECT
      </div>

      <h1 style="
        margin:0;
        font-size:26px;
      ">
        Abubakri's Grant Portal
      </h1>

      <p style="
        margin:8px 0 0;
        color:#dbeafe;
        font-size:14px;
      ">
        Software Development Demonstration
      </p>

    </div>

    <!-- DEMO WARNING -->
    <div style="
      margin:24px;
      padding:16px;
      background:#fff7ed;
      border:1px solid #fed7aa;
      border-radius:10px;
      color:#9a3412;
    ">

      <div style="
        font-weight:bold;
        font-size:14px;
        margin-bottom:6px;
      ">
        ⚠️ DEMO PROJECT — NOT A REAL GOVERNMENT PROGRAM
      </div>

      <div style="
        font-size:13px;
        line-height:1.6;
      ">
        This email was generated by a fictional software project
        created for development, learning, and demonstration purposes.
        It is not affiliated with or endorsed by any government agency.
      </div>

    </div>

    <!-- CONTENT -->
    <div style="
      padding:0 28px 30px;
    ">

      ${content}

    </div>

    <!-- FOOTER -->
    <div style="
      background:#f8fafc;
      border-top:1px solid #e2e8f0;
      padding:22px;
      text-align:center;
    ">

      <p style="
        margin:0 0 8px;
        font-size:13px;
        font-weight:bold;
        color:#334155;
      ">
        Built by Abubakri 👨‍💻
      </p>

      <p style="
        margin:0;
        font-size:12px;
        line-height:1.6;
        color:#64748b;
      ">
        Full-Stack Developer<br/>
        Educational &amp; Software Demonstration Project
      </p>

      <p style="
        margin:14px 0 0;
        font-size:11px;
        color:#94a3b8;
      ">
        DEMO ONLY • NOT AN OFFICIAL GOVERNMENT SERVICE
      </p>

    </div>

  </div>

</body>
</html>
`;

/* -------------------------------------------------------------------------- */
/* EMAIL TEMPLATES                                                            */
/* -------------------------------------------------------------------------- */

export const emailTemplates = {

  /* ------------------------------------------------------------------------ */
  /* SIGNUP                                                                    */
  /* ------------------------------------------------------------------------ */

  signupConfirmation: (
    firstName: string,
    refNumber: string,
  ) => ({
    subject: `Welcome to Abubakri's Grant Portal Demo - ${refNumber}`,

    html: emailLayout(
      "Welcome to Abubakri's Grant Portal",
      `
        <h2 style="
          margin:0 0 12px;
          color:#1e293b;
        ">
          Welcome, ${firstName}! 👋
        </h2>

        <p style="
          font-size:15px;
          line-height:1.7;
          color:#475569;
        ">
          Your account has successfully been created in the
          <strong>Abubakri's Grant Portal Demo</strong>.
        </p>

        <div style="
          margin:24px 0;
          padding:20px;
          background:#f8fafc;
          border:1px solid #e2e8f0;
          border-radius:12px;
        ">

          <div style="
            font-size:12px;
            color:#64748b;
            margin-bottom:6px;
          ">
            DEMO REFERENCE NUMBER
          </div>

          <div style="
            font-size:22px;
            font-weight:bold;
            letter-spacing:1px;
            color:#2563eb;
            font-family:monospace;
          ">
            ${refNumber}
          </div>

        </div>

        <h3 style="color:#1e293b;">
          What's next?
        </h3>

        <p style="
          font-size:14px;
          line-height:1.7;
          color:#475569;
        ">
          You can return to the portal to explore your dashboard,
          review the available demo grant packages, and test the
          application's features.
        </p>

        <div style="
          margin-top:24px;
          padding:15px;
          background:#eff6ff;
          border-radius:10px;
          color:#1e40af;
          font-size:13px;
          line-height:1.6;
        ">
          <strong>Developer note:</strong>
          This notification demonstrates automated transactional
          email functionality using Nodemailer.
        </div>
      `,
    ),
  }),

  /* ------------------------------------------------------------------------ */
  /* ADMIN NEW USER                                                            */
  /* ------------------------------------------------------------------------ */

  adminNewUserRegistered: (user: {
    firstName: string;
    lastName: string;
    email: string;
    phone: string;
    dateOfBirth?: string | Date;
    occupation?: string;
    city?: string;
    state?: string;
    country?: string;
    refNumber: string;
  }) => ({
    subject: `New Demo User Registered - ${user.firstName} ${user.lastName}`,

    html: emailLayout(
      "New Demo User",
      `
        <h2 style="margin:0 0 12px;color:#1e293b;">
          New Demo User Registered 🔔
        </h2>

        <p style="
          color:#475569;
          font-size:14px;
          line-height:1.6;
        ">
          A new user has registered on your development project.
        </p>

        <div style="
          margin:22px 0;
          border:1px solid #e2e8f0;
          border-radius:12px;
          overflow:hidden;
        ">

          <div style="padding:13px;border-bottom:1px solid #e2e8f0;">
            <strong>Name:</strong>
            ${user.firstName} ${user.lastName}
          </div>

          <div style="padding:13px;border-bottom:1px solid #e2e8f0;">
            <strong>Email:</strong>
            ${user.email}
          </div>

          <div style="padding:13px;border-bottom:1px solid #e2e8f0;">
            <strong>Phone:</strong>
            ${user.phone}
          </div>

          <div style="padding:13px;border-bottom:1px solid #e2e8f0;">
            <strong>Reference:</strong>
            ${user.refNumber}
          </div>

          <div style="padding:13px;border-bottom:1px solid #e2e8f0;">
            <strong>Occupation:</strong>
            ${user.occupation || "N/A"}
          </div>

          <div style="padding:13px;">
            <strong>Location:</strong>
            ${user.city || ""}, ${user.state || ""}, ${user.country || ""}
          </div>

        </div>

        <p style="
          font-size:12px;
          color:#64748b;
        ">
          Registered at: ${new Date().toUTCString()}
        </p>
      `,
    ),
  }),

  /* ------------------------------------------------------------------------ */
  /* USER SIGN IN                                                              */
  /* ------------------------------------------------------------------------ */

  adminUserSignedIn: (user: {
    firstName: string;
    lastName: string;
    email: string;
    refNumber: string;
  }) => ({
    subject: `Demo User Signed In - ${user.firstName} ${user.lastName}`,

    html: emailLayout(
      "Demo User Sign In",
      `
        <h2 style="margin:0 0 12px;color:#1e293b;">
          User Sign-In Activity 🔐
        </h2>

        <p style="
          color:#475569;
          font-size:14px;
          line-height:1.6;
        ">
          A user has signed into your development application.
        </p>

        <div style="
          margin:22px 0;
          padding:20px;
          background:#f8fafc;
          border:1px solid #e2e8f0;
          border-radius:12px;
          line-height:2;
          font-size:14px;
        ">

          <strong>Name:</strong>
          ${user.firstName} ${user.lastName}<br/>

          <strong>Email:</strong>
          ${user.email}<br/>

          <strong>Reference:</strong>
          ${user.refNumber}<br/>

          <strong>Time:</strong>
          ${new Date().toUTCString()}

        </div>
      `,
    ),
  }),

  /* ------------------------------------------------------------------------ */
  /* PACKAGE SELECTION                                                         */
  /* ------------------------------------------------------------------------ */

  packageSelectionEmail: (
    firstName: string,
    refNumber: string,
    grantAmount: number,
    fee: number,
  ) => ({
    subject: `Demo Grant Package Selected - ${refNumber}`,

    html: emailLayout(
      "Demo Grant Package",
      `
        <h2 style="margin:0 0 12px;color:#1e293b;">
          Package Selected 🎯
        </h2>

        <p style="
          color:#475569;
          font-size:14px;
          line-height:1.6;
        ">
          Hi ${firstName}, you selected a grant package
          inside the demonstration application.
        </p>

        <div style="
          margin:22px 0;
          padding:20px;
          background:#f8fafc;
          border:1px solid #e2e8f0;
          border-radius:12px;
        ">

          <p>
            <strong>Demo Reference:</strong>
            ${refNumber}
          </p>

          <p>
            <strong>Demo Grant Amount:</strong>
            $${grantAmount.toLocaleString()}
          </p>

          <p>
            <strong>Demo Processing Fee:</strong>
            $${fee.toLocaleString()}
          </p>

        </div>

        <div style="
          padding:15px;
          background:#fef2f2;
          border:1px solid #fecaca;
          border-radius:10px;
          color:#991b1b;
          font-size:13px;
          line-height:1.6;
        ">
          These amounts are fictional values used only for
          demonstrating the application's workflow.
          No real grant or payment is being offered.
        </div>
      `,
    ),
  }),

  /* ------------------------------------------------------------------------ */
  /* PAYMENT CONFIRMATION                                                      */
  /* ------------------------------------------------------------------------ */

  paymentConfirmation: (
    firstName: string,
    refNumber: string,
    grantAmount: number,
  ) => ({
    subject: `Demo Payment Status - ${refNumber}`,

    html: emailLayout(
      "Demo Payment Status",
      `
        <h2 style="
          margin:0 0 12px;
          color:#16a34a;
        ">
          Demo Payment Status Recorded ✓
        </h2>

        <p style="
          color:#475569;
          font-size:14px;
          line-height:1.7;
        ">
          Hi ${firstName}, your payment-status action has been
          recorded inside the demonstration application.
        </p>

        <div style="
          margin:22px 0;
          padding:20px;
          background:#f8fafc;
          border:1px solid #e2e8f0;
          border-radius:12px;
        ">

          <p>
            <strong>Reference:</strong>
            ${refNumber}
          </p>

          <p>
            <strong>Demo Grant Amount:</strong>
            $${grantAmount.toLocaleString()}
          </p>

        </div>

        <div style="
          padding:15px;
          background:#ecfdf5;
          border:1px solid #a7f3d0;
          border-radius:10px;
          color:#065f46;
          font-size:13px;
          line-height:1.6;
        ">
          This is a software-development demonstration.
          No real payment or grant transaction has occurred.
        </div>
      `,
    ),
  }),

  /* ------------------------------------------------------------------------ */
  /* PASSWORD RESET                                                            */
  /* ------------------------------------------------------------------------ */

  passwordReset: (resetUrl: string) => ({
    subject: "Reset Your Demo Portal Password",

    html: emailLayout(
      "Password Reset",
      `
        <h2 style="margin:0 0 12px;color:#1e293b;">
          Password Reset 🔑
        </h2>

        <p style="
          color:#475569;
          font-size:14px;
          line-height:1.7;
        ">
          We received a request to reset your password
          for Abubakri's Grant Portal Demo.
        </p>

        <div style="text-align:center;margin:28px 0;">

          <a
            href="${resetUrl}"
            style="
              display:inline-block;
              background:#2563eb;
              color:white;
              padding:13px 24px;
              border-radius:8px;
              text-decoration:none;
              font-weight:bold;
              font-size:14px;
            "
          >
            Reset Demo Password
          </a>

        </div>

        <p style="
          font-size:12px;
          color:#64748b;
          line-height:1.6;
        ">
          This reset link expires in 1 hour.
          If you did not request this, you can safely ignore
          this email.
        </p>
      `,
    ),
  }),
};